
// GET BLOG
export const GET_BLOGS_REQUEST = 'GET_BLOGS_REQUEST';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'
export const GET_BLOGS_ERROR = 'GET_BLOGS_ERROR'


// CREATE BLOG
export const CREATE_BLOGS_REQUEST = 'CREATE_BLOGS_REQUEST';
export const CREATE_BLOGS_SUCCESS = 'CREATE_BLOGS_SUCCESS'
export const CREATE_BLOGS_ERROR = 'CREATE_BLOGS_ERROR'


// SINGLE BLOG
export const SINGLE_BLOGS_REQUEST = 'SINGLE_BLOGS_REQUEST';
export const SINGLE_BLOGS_SUCCESS = 'SINGLE_BLOGS_SUCCESS'
export const SINGLE_BLOGS_ERROR = 'SINGLE_BLOGS_ERROR'

// EDIT BLOG
export const EDIT_BLOGS_REQUEST = 'EDIT_BLOGS_REQUEST';
export const EDIT_BLOGS_SUCCESS = 'EDIT_BLOGS_SUCCESS'
export const EDIT_BLOGS_ERROR = 'EDIT_BLOGS_ERROR'


// DELETE BLOG
export const DELETE_BLOGS_REQUEST = 'DELETE_BLOGS_REQUEST';
export const DELETE_BLOGS_SUCCESS = 'DELETE_BLOGS_SUCCESS'
export const DELETE_BLOGS_ERROR = 'DELETE_BLOGS_ERROR'
