
// WALLET
export const GET_WALLET_REQUEST = 'GET_WALLET_REQUEST';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS'
export const GET_WALLET_FINALLY = 'GET_WALLET_FINALLY'


// TRANSACTIONS
export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'
export const GET_TRANSACTIONS_FINALLY = 'GET_TRANSACTIONS_FINALLY'


// WITHDRAW
export const GET_WITHDRAW_REQUEST = 'GET_WITHDRAW_REQUEST';
export const GET_WITHDRAW_SUCCESS = 'GET_WITHDRAW_SUCCESS'
export const GET_WITHDRAW_FINALLY = 'GET_WITHDRAW_FINALLY'

// WITHDRAW
export const ACTIVATE_WALLET_REQUEST = 'ACTIVATE_WALLET_REQUEST';
export const ACTIVATE_WALLET_SUCCESS = 'ACTIVATE_WALLET_SUCCESS'
export const ACTIVATE_WALLET_FINALLY = 'ACTIVATE_WALLET_FINALLY'

// WITHDRAW
export const DEACTIVATE_WALLET_REQUEST = 'DEACTIVATE_WALLET_REQUEST';
export const DEACTIVATE_WALLET_SUCCESS = 'DEACTIVATE_WALLET_SUCCESS'
export const DEACTIVATE_WALLET_FINALLY = 'DEACTIVATE_WALLET_FINALLY'

// WITHDRAW
export const RETURN_WALLET_REQUEST = 'RETURN_WALLET_REQUEST';
export const RETURN_WALLET_SUCCESS = 'RETURN_WALLET_SUCCESS'
export const RETURN_WALLET_FINALLY = 'RETURN_WALLET_FINALLY'


// WALLETUSERS
export const GET_WALLETUSERS_REQUEST = 'GET_WALLETUSERS_REQUEST';
export const GET_WALLETUSERS_SUCCESS = 'GET_WALLETUSERS_SUCCESS'
export const GET_WALLETUSERS_FINALLY = 'GET_WALLETUSERS_FINALLY'

// WALLETUSERS
export const GET_WALLETUSERSAll_REQUEST = 'GET_WALLETUSERSAll_REQUEST';
export const GET_WALLETUSERSAll_SUCCESS = 'GET_WALLETUSERSAll_SUCCESS'
export const GET_WALLETUSERSAll_FINALLY = 'GET_WALLETUSERSAll_FINALLY'