
// NOTIFICATIONS
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FINALLY = 'GET_NOTIFICATIONS_FINALLY'


// DELETE
export const DELETE_NOTIFICATION_REQUEST = 'DELETE_NOTIFICATION_REQUEST';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS'
export const DELETE_NOTIFICATION_FINALLY = 'DELETE_NOTIFICATION_FINALLY'


// DELETE
export const GET_SEND_NOTIFICATION_SPECIFIC_REQUEST = 'GET_SEND_NOTIFICATION_SPECIFIC_REQUEST';
export const GET_SEND_NOTIFICATION_SPECIFIC_SUCCESS = 'GET_SEND_NOTIFICATION_SPECIFIC_SUCCESS'
export const GET_SEND_NOTIFICATION_SPECIFIC_FINALLY = 'GET_SEND_NOTIFICATION_SPECIFIC_FINALLY'

// DELETE
export const GET_SEND_NOTIFICATION_REQUEST = 'GET_SEND_NOTIFICATION_REQUEST';
export const GET_SEND_NOTIFICATION_SUCCESS = 'GET_SEND_NOTIFICATION_SUCCESS'
export const GET_SEND_NOTIFICATION_FINALLY = 'GET_SEND_NOTIFICATION_FINALLY'

// DELETE
export const GET_USER_NOTIFICATION_REQUEST = 'GET_USER_NOTIFICATION_REQUEST';
export const GET_USER_NOTIFICATION_SUCCESS = 'GET_USER_NOTIFICATION_SUCCESS'
export const GET_USER_NOTIFICATION_FINALLY = 'GET_USER_NOTIFICATION_FINALLY'